# Generated by Django 5.1 on 2024-12-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroVentas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='monto',
            new_name='total_venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_boleta',
            field=models.IntegerField(default=None),
        ),
    ]
