# Generated by Django 5.1 on 2024-12-16 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionInventario', '0003_alter_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
